version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./internal/db/migrations:/docker-entrypoint-initdb.d  # Auto-runs SQL scripts on startup

volumes:
  mysql_data: