// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/inasknh/simple-poke-app/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateBerry provides a mock function with given fields: ctx, berries
func (_m *Repository) CreateBerry(ctx context.Context, berries []model.Berry) error {
	ret := _m.Called(ctx, berries)

	if len(ret) == 0 {
		panic("no return value specified for CreateBerry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Berry) error); ok {
		r0 = rf(ctx, berries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchBerries provides a mock function with given fields: ctx
func (_m *Repository) FetchBerries(ctx context.Context) (*model.BerriesResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchBerries")
	}

	var r0 *model.BerriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.BerriesResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.BerriesResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BerriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
