// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/inasknh/simple-poke-app/internal/api"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetBerries provides a mock function with given fields: ctx, request
func (_m *Client) GetBerries(ctx context.Context, request api.BerriesRequest) (*api.BerriesResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetBerries")
	}

	var r0 *api.BerriesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.BerriesRequest) (*api.BerriesResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.BerriesRequest) *api.BerriesResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.BerriesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.BerriesRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
